title: Olga Suslova
name: Underwater world
description: Oil and watercolor paintings by Olga Suslova
view_collection: Scroll Down
about:
    title: Made with love
    description: I'm fascinated by everything related to the sea. The beauty
                 of shades and shapes of shells and stones and the amazing
                 creatures living in the ocean. Listening to the waves crashing
                 at shore gives me a deep sense of peace and relaxation.
galleries:
  - name: Deep Blue
    image: deep-blue.jpg
  - name: Watercolor
    image: watercolor.jpg
  - name: Baroque
    image: baroque.jpg
  - name: Sea Shore
    image: sea-shore.jpg
  - name: Blue Day
    image: blue-day.jpg
  - name: Fossils
    image: fossils.jpg
  - name: Forest
    image: forest.jpg
  - name: Close Up
    image: close-up.jpg
  - name: Landscape
    image: landscape.jpg
