title: Olga Suslova
name: Underwater world
description: Oil and watercolor paintings by Olga Suslova
view_collection: Scroll Down
copyright: Copyright Olga Suslova &copy; 2016. All Rights Reserved.

about:
    title: Olga Suslova
    description: Marine life and wild life artist, a member of the
                 Ocean Artists Society.

footer:
    about: About Me
    description: >
                 I am an artist based in Tel Aviv, Israel. I received my education
                 at Arts Academy of St. Petersburg, Russia. In the beginning of my
                 career I worked as a stage designer but now I dedicate all my time
                 to painting. I enjoy my working time, it's the best time for me.
                 What I try to express through my painting is a sense of harmony in
                 the nature, the magic that is hidden even in the smallest things.
                 I agree with Andrew Wyeth when he says: "One's art goes as far
                 and as deep as one's love goes".

links:
  facebook: https://www.facebook.com/olga.suslova.1
  etsy: https://www.etsy.com/

shop:
  buy_prints: Buy Prints
  prints: Prints
  originals: Originals

galleries:
  - name: Deep Blue
    slug: deep-blue
    image: deep-blue.jpg
    items:
    - name: Beautiful Beast
      image: 01-beautiful-beast.jpg
      description: oil on canvas 80x80
    - name: Deep Blue
      image: 02-deep-blue.jpg
      description: oil on canvas 80x60 cms
    - name: Nocturne
      image: 03-nocturne.jpg
      description: oil on canvas 60x60 cms
    - name: Small Piece of the Sea
      image: 04-small-piece-of-the-sea.jpg
      description: oil on canvas 60x60 cms
    - name: Newborn
      image: 05-newborn.jpg
      description: oil on canvas 50x40 cm
    - name: Red Reef
      image: 06-red-reef.jpg
      description: oil on canvas 80x150 cm
    - name: To the Deep
      image: 07-to-the-deep.jpg
      description: oil on canvas 160x150 cm
    - name: Happy Cuttlefish
      image: 08-happy-cuttlefish.jpg
      description: oil on canvas 60x60
    - name: The Big Fish
      image: 09-the-big-fish.jpg
      description: oil on canvas 100x100 cm
    - name: Green Reef
      image: 10-green-reef.jpg
      description: oil on canvas 80x80 cm
    - name: Big Parrot Fish
      image: 11-big-parrot-fish.jpg
      description: oil on canvas 80x100 cm
    - name: Turquoise Morning
      image: 12-turquoise-morning.jpg
      description: oil on canvas 100x100 cm
    - name: Mirrored Turtle
      image: 13-mirrored-turtle.jpg
      description: oil on canvas 100x100 cm  x 2
    - name: Sunset Flight
      image: 14-sunset-flight.jpg
      description: oil on canvas 80x80 x 3
    - name: Blue Ringed Octopus
      image: 15-blue-ringed-octopus.jpg
      description: oil on canvas 45x45 cm

  - name: Watercolor
    slug: watercolor
    image: watercolor.jpg
    items:
    - name: Sleeping Whales
      image: 01-sleeping-whales.jpg
      description: watercolor on paper 85x60 cm
    - name: Gulf Stream
      image: 02-gulf-stream.jpg
      description: watercolor on paper 50x70 cm
    - name: Gulf Stream Series
      image: 03-gulf-stream-series.jpg
      description: watercolor on paper 65x80
    - name: Gulf Stream Series
      image: 04-gulf-stream-series.jpg
      description: watercolor on paper 65x80
    - name: Sea Turtle
      image: 05-sea-turtle.jpg
      description: watercolor on paper 60x60 cm
    - name: Sea Dragon
      image: 06-sea-dragon.jpg
      description: watercolor on paper
    - name: Melting Ice
      image: 07-melting-ice.jpg
      description: watercolor on paper
    - name: Polar Sea
      image: 08-polar-sea.jpg
      description: watercolor on paper
    - name: Melting Ice
      image: 09-melting-ice.jpg
      description: watercolor on paper
    - name: Polar Sea
      image: 10-polar-sea.jpg
      description: watercolor on paper
    - name: Mola Mola
      image: 11-mola-mola.jpg
      description: watercolour on paper 50x35 cm
    - name: Happy Whale
      image: 12-happy-whale.jpg
      description: watercolor on paper
    - name: Polar Sea
      image: 13-polar-sea.jpg
      description: watercolor on paper
    - name: Polar Sea
      image: 14-polar-sea.jpg
      description: watercolor on paper
    - name: Polar Sea
      image: 15-polar-sea.jpg
      description: watercolor on paper
    - name: Hello!
      image: 16-hello!.jpg
      description: watercolor on paper
    - name: Whales
      image: 17-whales.jpg
      description: watercolor on paper
    - name: Polar Sea
      image: 18-polar-sea.jpg
      description: watercolor on paper
    - name: Polar Sea
      image: 19-polar-sea.jpg
      description: watercolor on paper
    - name: Gulf Stream Series
      image: 20-gulf-stream-series.jpg
      description: watercolor on paper 70x50 cm
    - name: Polar Sea
      image: 21-polar-sea.jpg
      description: watercolor on paper

  - name: Baroque
    slug: baroque
    image: baroque.jpg
    items:
    - name: Queen of the Reef
      image: 01-queen-of-the-reef.jpg
      description: oil on canvas 100x80
    - name: Red Corals for the Queen
      image: 02-triptych-baroque---red-corals-for-the-queen.jpg
      description: oil on canvas 100x80
    - name: Guards
      image: 03-triptych-baroque---guards.jpg
      description: oil on canvas 100x80
    - name: King and His Treasures
      image: 04-triptych-baroque---king-and-his-treasures.jpg
      description: oil on canvas 100x80
    - name: Triptych BAROQUE
      image: 05-triptych-baroque.jpg
      description: oil on canvas 100x80 cm x 3
    - name: Morning on the Coral Reef
      image: 06-morning-on-the-coral-reef.jpg
      description: oil on canvas 130x80 cm
    - name: Coral Reef
      image: 07-coral-reef.jpg
      description: oil on canvas 80x70 cm
    - name: Coral Reef
      image: 08-coral-reef.jpg
      description: oil on canvas 80x80 cm
    - name: Caw Fish
      image: 09-caw-fish.jpg
      description: oil on canvas 80x80 cm
    - name: Sunset in the Coral Garden
      image: 10-sunset-in-the-coral-garden.jpg
      description: oil on canvas 100x100 cm

  - name: Sea Shore
    slug: sea-shore
    image: sea-shore.jpg
    items:
    - name: Eilat , Detail
      image: 01-eilat-,-detail.jpg
      description: watercolor on paper 50x70 cm
    - name: Herzliya
      image: 02-herzliya.jpg
      description: watercolor on paper 50x70 cm
    - name: Eilat
      image: 03-eilat.jpg
      description: watercolor on paper 50x70 cm
    - name: Eilat
      image: 04-eilat.jpg
      description: watercolor on paper 50x70 cm
    - name: Venece
      image: 05-venece.jpg
      description: watercolor on paper 50x70 cm
    - name: Shells on Sand
      image: 06-shells-on-sand.jpg
      description: watercolour on paper 35x50 cm
    - name: Shells on the Sand
      image: 07-shells-on-the-sand.jpg
      description: watercolour on paper 35x50 cm
    - name: Dead Sea
      image: 08-dead-sea.jpg
      description: watercolor on paper 50x70 cm
    - name: Kineret
      image: 09-kineret.jpg
      description: watercolor on paper 50x70 cm
    - name: Broken Shells, Bulgaria
      image: 10-broken-shells-of-the-black-sea,-bulgaria.jpg
      description: watercolor on paper
    - name: Akko, Detail
      image: 11-akko,-detail.jpg
      description: watercolor on paper 50x70 cm
    - name: Missing
      image: 12-.jpg
      description: Missing
    - name: Eilat, Detail
      image: 13-eilat,-detail.jpg
      description: watercolor on paper 50x70 cm
    - name: Crete
      image: 14-crete.jpg
      description: watercolor on paper 50x70 cm
    - name: Crete, Detail
      image: 15-crete,-detail.jpg
      description: watercolor on paper 50x70 cm
    - name: Venice
      image: 16-venice.jpg
      description: watercolour on paper 50x70 cm
    - name: Herzliya
      image: 17-herzliya.jpg
      description: watercolour on paper 35x50 cm
    - name: Rosh HaNikra
      image: 18-rosh-hanikra.jpg
      description: watercolor on paper 50x70 cm
    - name: Netania
      image: 19-netania.jpg
      description: watercolour on paper 50x70 cm
    - name: Haifa
      image: 20-haifa.jpg
      description: watercolour on paper 50x70 cm

  - name: Blue Day
    slug: blue-day
    image: blue-day.jpg
    items:
    - name: Blue Day
      image: 01-blue-day.jpg
      description: oil on canvas 80x80 cm
    - name: Five Stars
      image: 02-five-stars.jpg
      description: oil on canvas 100x100 cm
    - name: The Owner of Treasures
      image: 03-the-owner-of-treasures.jpg
      description: oil on canvas 60x60 cm
    - name: Lionfish
      image: 04-lionfish.jpg
      description: oil on canvas 60x50 cm
    - name: Crystal River
      image: 05-crystal-river.jpg
      description: oil on canvas 80x60 cm
    - name: Coral Reef
      image: 06-coral-reef.jpg
      description: oil on canvas 80x60 cm
    - name: Morning in Eilat
      image: 07-morning-in-eilat.jpg
      description: oil on canvas 80x150 cm
    - name: Sea Turtle
      image: 08-sea-turtle.jpg
      description: oil on canvas 80x80 cm
    - name: Infinity
      image: 09-infinity.jpg
      description: oil on canvas 80x100 cm
    # - name: Mirrored Turtle
    #   image: 10-mirrored-turtle.jpg
    #   description: oil on canvas 100x100 x 2

  - name: Desert
    slug: desert
    image: desert.jpg
    items:
    - name: Desert Landscape
      image: 01-desert-landscape.jpg
      description: watercolor on paper 28x60 cm
    - name: Desert Landscape
      image: 02-desert-landscape.jpg
      description: watercolor on paper 23x50 cm
    - name: Desert Landscape
      image: 03-desert-landscape.jpg
      description: watercolor on paper 28x60 cm
    - name: Desert Landscape
      image: 04-desert-landscape.jpg
      description: watercolor on paper 28x60 cm
    - name: Desert Landscape
      image: 05-desert-landscape.jpg
      description: watercolor on paper 28x60 cm
    - name: Desert Landscape
      image: 06-desert-landscape.jpg
      description: watercolor on paper 23x50 cm
    - name: Desert Landscape
      image: 07-desert-landscape.jpg
      description: mixed media on cardboard 25х70 cm
    - name: Desert Landscape
      image: 08-desert-landscape.jpg
      description: mixed media on cardboard 25х70 cm
    - name: Desert Landscape
      image: 09-desert-landscape.jpg
      description: mixed media on cardboard 25х70 cm
    - name: Desert Landscape
      image: 10-desert-landscape.jpg
      description: mixed media on cardboard 25х70 cm
    - name: Desert Landscape
      image: 11-desert-landscape.jpg
      description: mixed media on cardboard 25х70 cm
    - name: Desert Landscape
      image: 12-desert-landscape.jpg
      description: mixed media on cardboard 25х70 cm

  - name: Fossils
    slug: fossils
    image: fossils.jpg
    items:
    - name: Fossils
      image: 01-fossils.jpg
      description: oil on canvas 80x80 cm
    - name: Red Rocks
      image: 02-red-rocks.jpg
      description: oil on canvas 80x80 cms
    - name: Misty Morning
      image: 03-misty-morning.jpg
      description: oil on canvas 80x80 cm
    - name: Big Ammonite
      image: 04-big-ammonite.jpg
      description: oil on canvas 80x80 cms
    - name: Shells and Butterflies
      image: 05-shells-and-butterflies.jpg
      description: oil on canvas 80x80 cms
    - name: Sad Cuttlefish
      image: 06-sad-cuttlefish.jpg
      description: oil on canvas 50x40 cm
    - name: Misty Lagoon
      image: 07-misty-lagoon.jpg
      description: oil on canvas 80x60 cms
    - name: Atlantis
      image: 08-atlantis,-oil-on-canvas-140x110x2.jpg
      description: Oil on Canvas 140x110x2
    - name: Napoleon Fish
      image: 09-napoleon-fish.jpg
      description: oil on canvas 50x60 cm
    - name: In the Cave
      image: 10-in-the-cave.jpg
      description: oil on canvas 80x80 cm
    - name: Zeus Faber
      image: 11-zeus-faber,-oil-on-canvas-60x60-cm.jpg
      description: Oil on Canvas 60x60 Cm
    - name: Still Life With Shells
      image: 12-still-life-with-shells.jpg
      description: oil on canvas 60x60 cms
    - name: Stillife on White
      image: 13-stillife-on-white.jpg
      description: Oil on canvas, 50x60 cm
    - name: Stillife on Black
      image: 14-stillife-on-black.jpg
      description: oil on canvas 25x35 cm
    - name: Sea Collection
      image: 15-sea-collection.jpg
      description: oil on canvas 80x60 cms

  - name: Forest
    slug: forest
    image: forest.jpg
    items:
    - name: The Last Minute
      image: 01-the-last-minute.jpg
      description: oil on canvas 100x70 cm
    - name: Mimicry
      image: 02-mimicry.jpg
      description: oil on canvas 80x80 cm
    - name: Life in the Grass
      image: 03-life-in-the-grass.jpg
      description: oil on canvas 60x60 cm
    - name: Going Green
      image: 04-going-green.jpg
      description: oil on canvas 60x60 cm
    - name: Enjoying the Sunset
      image: 05-enjoying-the-sunset.jpg
      description: oil on canvas 60x60 cm

  - name: Close Up
    slug: close-up
    image: close-up.jpg
    items:
    - name: Close up
      image: 01-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 02-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 03-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 04-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 05-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 06-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 07-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 08-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 09-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 10-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 11-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 12-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 13-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 14-oil-on-canvas.jpg
      description: Oil on Canvas
    - name: Close up
      image: 15-oil-on-canvas.jpg
      description: Oil on Canvas
