title: Olga Suslova
name: Underwater world
description: Oil and watercolor paintings by Olga Suslova
view_collection: Scroll Down
about:
    title: Made with love
    description: "What I try to express through my painting is a sense of harmony
                 in the nature, the magic that is hidden even in the smallest things.
                 I agree with Andrew Wyeth when he says: <cite>&ldquo;One's art goes
                 as far and as deep as one's love goes&rdquo;</cite>."
footer:
    about: About Me
    description: I am an artist based in Tel Aviv, Israel. I received my education
                 at Arts Academy of St. Petersburg, Russia. In the beginning of my
                 career I worked as a stage designer but now I dedicate all my time
                 to painting. I enjoy my working time, it's the best time for me.
links:
  facebook: https://www.facebook.com/olga.suslova.1
  etsy: https://www.etsy.com/
shop:
  buy_prints: Buy Prints
  prints: Prints
  originals: Originals
copyright: Copyright Olga Suslova &copy; 2016. All Rights Reserved.
galleries:
  - name: Deep Blue
    image: deep-blue.jpg
  - name: Watercolor
    image: watercolor.jpg
  - name: Baroque
    image: baroque.jpg
  - name: Sea Shore
    image: sea-shore.jpg
  - name: Blue Day
    image: blue-day.jpg
  - name: Fossils
    image: fossils.jpg
  - name: Forest
    image: forest.jpg
  - name: Close Up
    image: close-up.jpg
  - name: Landscape
    image: landscape.jpg
